"""Add OIDC identity table

Revision ID: 5e326203c1fc
Revises: fd531f8868b1
Create Date: 2025-11-06 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5e326203c1fc"
down_revision: str | None = "fd531f8868b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create oidcidentity table for OIDC authentication."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oidcidentity",
        sa.Column("provider_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("issuer", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("picture", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("oidcidentity", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_oidcidentity_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_oidcidentity_issuer"), ["issuer"], unique=False)
        batch_op.create_index(batch_op.f("ix_oidcidentity_provider_name"), ["provider_name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_oidcidentity_provider_user_id"), ["provider_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_oidcidentity_user_id"), ["user_id"], unique=False)

    # Create composite index for faster lookups by provider and subject
    with op.batch_alter_table("oidcidentity", schema=None) as batch_op:
        batch_op.create_index(
            "ix_oidcidentity_provider_subject",
            ["provider_name", "provider_user_id"],
            unique=True,
        )
        batch_op.create_index(
            "ix_oidcidentity_issuer_subject",
            ["issuer", "provider_user_id"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop oidcidentity table."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oidcidentity", schema=None) as batch_op:
        batch_op.drop_index("ix_oidcidentity_issuer_subject")
        batch_op.drop_index("ix_oidcidentity_provider_subject")
        batch_op.drop_index(batch_op.f("ix_oidcidentity_user_id"))
        batch_op.drop_index(batch_op.f("ix_oidcidentity_provider_user_id"))
        batch_op.drop_index(batch_op.f("ix_oidcidentity_provider_name"))
        batch_op.drop_index(batch_op.f("ix_oidcidentity_issuer"))
        batch_op.drop_index(batch_op.f("ix_oidcidentity_email"))

    op.drop_table("oidcidentity")
    # ### end Alembic commands ###
