"""Add audit log table

Revision ID: a8f7d3e2b4c1
Revises: 5e326203c1fc
Create Date: 2025-11-06 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a8f7d3e2b4c1"
down_revision: str | None = "5e326203c1fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create auditlog table for security event tracking."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auditlog",
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("result", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("provider_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("failure_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("auditlog", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auditlog_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_auditlog_event_type"), ["event_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_auditlog_provider"), ["provider"], unique=False)
        batch_op.create_index(batch_op.f("ix_auditlog_result"), ["result"], unique=False)
        batch_op.create_index(batch_op.f("ix_auditlog_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_auditlog_username"), ["username"], unique=False)

    # Create composite indexes for common queries
    with op.batch_alter_table("auditlog", schema=None) as batch_op:
        # Index for querying failed logins by username
        batch_op.create_index(
            "ix_auditlog_username_result",
            ["username", "result"],
            unique=False,
        )
        # Index for querying events by user and time
        batch_op.create_index(
            "ix_auditlog_user_id_created_at",
            ["user_id", "created_at"],
            unique=False,
        )
        # Index for querying events by provider and time
        batch_op.create_index(
            "ix_auditlog_provider_created_at",
            ["provider", "created_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop auditlog table."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auditlog", schema=None) as batch_op:
        batch_op.drop_index("ix_auditlog_provider_created_at")
        batch_op.drop_index("ix_auditlog_user_id_created_at")
        batch_op.drop_index("ix_auditlog_username_result")
        batch_op.drop_index(batch_op.f("ix_auditlog_username"))
        batch_op.drop_index(batch_op.f("ix_auditlog_user_id"))
        batch_op.drop_index(batch_op.f("ix_auditlog_result"))
        batch_op.drop_index(batch_op.f("ix_auditlog_provider"))
        batch_op.drop_index(batch_op.f("ix_auditlog_event_type"))
        batch_op.drop_index(batch_op.f("ix_auditlog_created_at"))

    op.drop_table("auditlog")
    # ### end Alembic commands ###
